package com.ecommerce.productservices.Model_Entity;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * This class represents a generic product entity in the e-commerce application.
 * It serves as a base class for specific product types.
 */
@Entity
@Getter
@Setter
@NoArgsConstructor
public class GenericProduct {

    /**
     * Unique identifier for the product (primary key).
     * This field is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Name of the product.
     */
    private String name;

    /**
     * Price of the product.
     */
    private int price;

    /**
     * Constructor for creating a new GenericProduct object.
     *
     * @param name  Name of the product.
     * @param price Price of the product.
     */
    public GenericProduct(String name, int price) {
        this.name = name;
        this.price = price;
    }
}
