package com.ecommerce.productservices.Model_Entity;

import jakarta.persistence.*; // Import all javax persistence annotations
import lombok.Getter;
import lombok.Setter;

import static jakarta.persistence.GenerationType.IDENTITY;

/**
 * This class represents a User entity in the E-commerce application.
 * It maps to an "ecommerce_user" table in the database.
 */
@Entity(name = "ecommerce_user")
@Getter // Lombok annotation for generating getters for all fields
@Setter // Lombok annotation for generating setters for all fields
public class User {

    /**
     * Unique identifier for the User (primary key)
     * Auto-generated by the database using IDENTITY strategy.
     */
    @Id
    @GeneratedValue(strategy = IDENTITY)
    private Long id;

    /**
     * Name of the User
     */
    private String name;

    /**
     * Email address of the User (unique)
     */
    @Column(unique = true)
    private String email;
}
